WebApplication1/Models/Date.cs
namespace WebApplication1.Models
{
    public class Date
    {
    }
}

WebApplication1/Models/IEnumerableList.cs
namespace WebApplication1.Models
{
    public interface IEnumerableList<T>
    {
    }
}

WebApplication1/Models/Policy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Policy
    {
        public int cover_amount { get; set; }

        public string payout_option { get; set; }

        public int policy_term { get; set; }

        public int payment_term { get; set; }

        public string plan_type { get; set; }

        public string add_on { get; set; }

        public string policy_start_date { get; set; }

        public string policy_end_date { get; set; }

        public bool policy_active_flag { get; set; }

        public string policy_applied { get; set; }
    }
}

WebApplication1/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ClaimController : Controller
    {
        // GET: Claim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using BusinessLayer;
using WebApplication1.Models;
using DataAcessLayer1;

/*
        public int Cover_Amount;
        public string Plan_Type;
        public string Add_on;
        public int policy_id;
*/

namespace WebApplication1.Controllers
{
    public class PaymentController : Controller
    {
        public Payment1Class Pa = new Payment1Class();



        /*cover_amount, plantttype,addon,policyid*/
        [HttpGet]

        public ActionResult Index(Policy cusObj)
        {

            Pa.GetCobverAmount();

            int Cover_amount = Pa.Cover_Amount;
            string Plan_type = Pa.Plan_Type;

            string Add_on = Pa.Add_on;

            int Policy_id = Pa.policy_id;


            ViewBag.PLAN = Plan_type;

            double CoverAmount = Cover_amount;

            double LAnnualPremium = Math.Round(CoverAmount / 250.6002, 2);
            double LMonthlyPremiuim = Math.Round(LAnnualPremium / 12, 2);

            double ELAnnualPremium = Math.Round(CoverAmount / 220.6002, 2);
            double ELMonthlyPremiuim = Math.Round(LAnnualPremium / 12, 2);

            if (Add_on != "")
            {


                LAnnualPremium = LAnnualPremium + 336;
                LMonthlyPremiuim = LMonthlyPremiuim + 28;

                ELAnnualPremium = ELAnnualPremium + 336;
                ELMonthlyPremiuim = ELMonthlyPremiuim + 28;
            }



            ViewData["LifeOptionAnnualPremium"] = LAnnualPremium;
            ViewData["LifeOptionMonthlyPremium"] = LMonthlyPremiuim;
            ViewData["ExtraLifeOptionAnnualPremium"] = ELAnnualPremium;
            ViewData["ExtraLifeOptionMonthlyPremium"] = ELMonthlyPremiuim;



            Response.Write(ViewData["LifeOptionAnnualPremium"]);

            return View();




        }
        [HttpPost]
        public ActionResult Index(PaymentBussinessLayer pa, Policy cusObj)
        {
            Pa.GetCobverAmount();

            int Cover_amount = Pa.Cover_Amount;
            string Plan_type = Pa.Plan_Type;

            string Add_on = Pa.Add_on;

            int Policy_id = Pa.policy_id;


            ViewBag.PLAN = Plan_type;

            double CoverAmount = Cover_amount;

            double LAnnualPremium = Math.Round(CoverAmount / 250.6002, 2);
            double LMonthlyPremiuim = Math.Round(LAnnualPremium / 12, 2);

            double ELAnnualPremium = Math.Round(CoverAmount / 220.6002, 2);
            double ELMonthlyPremiuim = Math.Round(LAnnualPremium / 12, 2);




            if (cusObj.add_on != "")
            {


                LAnnualPremium = LAnnualPremium + 336;
                LMonthlyPremiuim = LMonthlyPremiuim + 28;

                ELAnnualPremium = ELAnnualPremium + 336;
                ELMonthlyPremiuim = ELMonthlyPremiuim + 28;
            }



            ViewData["LifeOptionAnnualPremium"] = LAnnualPremium;
            ViewData["LifeOptionMonthlyPremium"] = LMonthlyPremiuim;
            ViewData["ExtraLifeOptionAnnualPremium"] = ELAnnualPremium;
            ViewData["ExtraLifeOptionMonthlyPremium"] = ELMonthlyPremiuim;

            Pa.AddPaymentDetails(Policy_id, pa.payment_mode, pa.policy_premium);





            return View();




        }


    }
}

WebApplication1/Views/AddCustomer/Create.cshtml
@model WebApplication1.Models.AddCustomer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>AddCustomer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.gender_, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.state_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state_name, "", new { @class = "text-danger" })*@

            @Html.DropDownList("gender_", "---choose---");

        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.date_of_birth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_of_birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date_of_birth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nri_flag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.nri_flag)
                @Html.ValidationMessageFor(model => model.nri_flag, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tobbaco_user_flag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.tobbaco_user_flag)
                @Html.ValidationMessageFor(model => model.tobbaco_user_flag, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address_Line1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address_Line1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address_Line1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address_Line2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address_Line2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address_Line2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, "State", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @* @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })*@
            @Html.DropDownList("state", "---choose---");
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominee_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nominee_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nominee_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Customer/Index.cshtml
@model WebApplication1.Models.AddCustomer

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>AddCustomer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gender_, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.gender_,
                    new SelectList(ViewBag.gender_, "Value", "Text"),
                    "Select gender",
                    new { @class = "form-control" });
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.State,
                    new SelectList(ViewBag.state, "Value", "Text"),
                    "Select gender",
                    new { @class = "form-control" });
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })

        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.date_of_birth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_of_birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date_of_birth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nri_flag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.nri_flag)
                @Html.ValidationMessageFor(model => model.nri_flag, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tobbaco_user_flag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.tobbaco_user_flag)
                @Html.ValidationMessageFor(model => model.tobbaco_user_flag, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address_Line1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address_Line1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address_Line1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address_Line2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address_Line2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address_Line2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Nominee_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nominee_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nominee_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Home/WhyThisPlan.cshtml
@{
    ViewBag.Title = "WhyThisPlan";
}
<br />


<div class="container-fluid">
    <center>
        <h2 style="color:#ed232a">
            Things which make this plan a must have term plan to protect your family's future.
        </h2>
    </center>
    <hr />
    <br />

    <div style=" color: #ed232a">
        <div class="panel" style="color: white; background-color: #004c8f">
            <div class="panel-heading">
                <h4>Whole life cover available.</h4>
            </div>
        </div>
        <div class="panel" style="color: white; background-color: #004c8f">
            <div class="panel-heading">
                <h4>Lumpsum payout on death or diagnosis of terminal illness.</h4>
            </div>
        </div>
        <div class="panel" style="color: white; background-color: #004c8f">
            <div class="panel-heading">
                <h4>Waiver of premiums in event of accidental total permanent disability or critical illness.</h4>
            </div>
        </div>
        <div class="panel" style="color: white; background-color: #004c8f">
            <div class="panel-heading">
                <h4>Receive monthly income for continued financial stability.</h4>
            </div>
        </div>
        <br />
        <br />

        <center>
            <a href="~/Customer/Index" class="btn btn-primary">Buy Term Plan</a>
        </center>
    </div>
</div>

WebApplication1/Views/Payment/Index.cshtml
@model BusinessLayer.PaymentBussinessLayer

@{ ViewBag.Title = "Index"; }





@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="jumbotron">
                    <h3 class="display-4">Please make a Payment</h3>
                    <hr class="my-1">

                    <div class="form-horizontal">
                        <h4>Payment</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.policy_id, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.policy_id, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.policy_id, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.payment_mode, "Payment Mode", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">

                                <label class="radio">
                                    @Html.RadioButtonFor(model => Model.payment_mode, "Credit Card", new { @name = "payment" })Credit Card
                                </label>
                                <label class="radio">
                                    @Html.RadioButtonFor(model => Model.payment_mode, "Debit Card", new { @name = "payment" })Debit Card

                                </label>
                                @Html.ValidationMessageFor(model => model.payment_mode, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.LabelFor(model => model.policy_premium, "Policy Premium", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">

                                @if (ViewBag.PLAN != "Life Option")
                                {
                <label class="radio">
                    @Html.RadioButtonFor(model => Model.policy_premium, ViewData["ExtraLifeOptionAnnualPremium"], new { @name = "payment" })Annual Premium of ?@ViewData["ExtraLifeOptionAnnualPremium"]
                </label>
                                    <label class="radio">
                                        @Html.RadioButtonFor(model => Model.policy_premium, ViewData["ExtraLifeOptionMonthlyPremium"], new { @name = "payment" })Monthly Premium of ?@ViewData["ExtraLifeOptionMonthlyPremium"]

                                    </label> }
                                                    else
                                                    {
                                    <label class="radio">
                                        @Html.RadioButtonFor(model => Model.policy_premium, ViewData["LifeOptionAnnualPremium"], new { @name = "payment" })Annual premium of ?@ViewData["LifeOptionAnnualPremium"]
                                    </label>
                                                        <label class="radio">
                                                            @Html.RadioButtonFor(model => Model.policy_premium, ViewData["LifeOptionMonthlyPremium"], new { @name = "payment" })Monthly Premium of ?@ViewData["LifeOptionMonthlyPremium"]

                                                        </label>}

                                @Html.ValidationMessageFor(model => model.policy_premium, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Pay" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}}

WebApplication1/Views/Policy/Details.cshtml
@model WebApplication1.Models.Policy
@{
    ViewBag.Title = "Details";
}



@{
    double CoverAmount = Model.cover_amount;

    double LAnnualPremium = Math.Round(CoverAmount / 250.6002, 2);
    double LOneTimePremiuim = Math.Round(LAnnualPremium * Model.payment_term, 2);

    double ELAnnualPremium = Math.Round(CoverAmount / 220.6002, 2);
    double ELOneTimePremiuim = Math.Round(LAnnualPremium * Model.payment_term, 2);




}

<div>



    <div class="jumbotron">
        <h3 class="display-4">Here is a summary of your plan</h3>
        <hr class="my-1">

        <dl class="dl-horizontal">

            <dt>
                Your Insurance Plan
            </dt>

            <dd>
                @Html.DisplayFor(model => model.plan_type)
            </dd>

            <hr class="my-1">

            <dt>
                Your Insurance Cover
            </dt>

            <dd>
                ₹@Html.DisplayFor(model => model.cover_amount)
            </dd>
            <hr class="my-1">

            @if (Model.plan_type == "Life Option")
            {
                <dt>
                    Nominee wil receive
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.payout_option) i.e Cover Amount of ₹@Html.DisplayFor(model => model.cover_amount) + additional of ₹@Html.DisplayFor(model => model.cover_amount) incase of death by accident.
                </dd>
            }
            else
            {
                <dt>
                    Nominee wil receive
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.payout_option) i.e Cover Amount of ₹@Html.DisplayFor(model => model.cover_amount)
                </dd>
            }

            <hr class="my-1">
            <dt>
                Policy Term
            </dt>

            <dd>
                @Html.DisplayFor(model => model.policy_term) Years
            </dd>
            <hr class="my-1">
            <dt>
                Premium paying term
            </dt>

            <dd>
                @Html.DisplayFor(model => model.payment_term) Years
            </dd>

            <hr class="my-1">

            @if (Model.add_on != "")
            {
                <dt>
                    Add Ons
                </dt>


                <dd>
                    @Html.DisplayFor(model => model.add_on) cover of ₹10,00,000.
                </dd>
                <hr class="my-1">

                LAnnualPremium = LAnnualPremium + 336;
                LOneTimePremiuim = LOneTimePremiuim + (Model.payment_term * 336);

                ELAnnualPremium = ELAnnualPremium + 336;
                ELOneTimePremiuim = ELOneTimePremiuim + (Model.payment_term * 336);

            }

            <dt>
                Annual Premium Amount
            </dt>

            @if (Model.plan_type == "Life Option")
            {
                <dd>
                    ₹@LAnnualPremium
                </dd>
            }
            else
            {
                <dd>
                    ₹@ELAnnualPremium
                </dd>
            }
            <hr class="my-1">
            <dt>
                One Time Payment Amount
            </dt>

            @if (Model.plan_type == "Life Option")
            {
                <dd>
                    ₹@LOneTimePremiuim
                </dd>
            }
            else
            {
                <dd>
                    ₹@ELOneTimePremiuim
                </dd>
            }






        </dl>
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
              
                <a class="btn btn-primary" href="@Url.Action("Index","Payment")" target="_blank">Continue to pay</a>

            </div>




        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Pay","Index","Payment")
    @Html.ActionLink("Back to List","Index")
</p>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>